#ifndef __REG_EM_BLE_RX_ISO_BUF_H_
#define __REG_EM_BLE_RX_ISO_BUF_H_

#define REG_EM_BLE_RX_ISO_BUF_SIZE 260

#define REG_EM_BLE_RX_ISO_BUF_BASE_ADDR 0x40128000


#endif // __REG_EM_BLE_RX_ISO_BUF_H_

