manifest:
  group-filter:
  - -optional
  - -babblesim
  projects:
  - name: hal_atmosic
    url: https://github.com/Atmosic/hal_atmosic
    revision: 0b2fc55bf469917c9a5d7dcbb5bfc0c368302ad9
    path: modules/hal/atmosic
  - name: hal_atmosic_lib
    url: https://github.com/Atmosic/hal_atmosic_lib
    revision: 650950134cfe49fdd1dc08d057f83f4d9bf64119
    path: modules/hal/atmosic_lib
  - name: mcuboot
    url: https://github.com/Atmosic/mcuboot
    revision: 7688baf013fe77eb28a7e055556a5f2452c10023
    path: bootloader/mcuboot
  - name: micro-ecc
    url: https://github.com/Atmosic/micro-ecc
    revision: d470cfa986a169bd3701b3be8451e741ac075ec5
    path: modules/crypto/micro-ecc
  - name: zephyr
    url: https://github.com/Atmosic/zephyr
    revision: 341d075a576284c505ce2120d2f9b2dcfd15d91b
    west-commands: scripts/west-commands.yml
  - name: cmsis
    url: https://github.com/zephyrproject-rtos/cmsis
    revision: 4b96cbb174678dcd3ca86e11e1f24bc5f8726da0
    path: modules/hal/cmsis
    groups:
    - hal
  - name: littlefs
    url: https://github.com/zephyrproject-rtos/littlefs
    revision: 009bcff0ed4853a53df8256039fa815bda6854dd
    path: modules/fs/littlefs
    groups:
    - fs
  - name: mbedtls
    url: https://github.com/zephyrproject-rtos/mbedtls
    revision: a78176c6ff0733ba08018cba4447bd3f20de7978
    path: modules/crypto/mbedtls
    groups:
    - crypto
  - name: tinycrypt
    url: https://github.com/zephyrproject-rtos/tinycrypt
    revision: 1012a3ebee18c15ede5efc8332ee2fc37817670f
    path: modules/crypto/tinycrypt
    groups:
    - crypto
  - name: zcbor
    url: https://github.com/zephyrproject-rtos/zcbor
    revision: 47f34dd7f5284e8750b5a715dee7f77c6c5bdc3f
    path: modules/lib/zcbor
  self:
    path: openair
    west-commands: west/west-commands.yml
