manifest:
  group-filter:
  - -babblesim
  - -optional
  projects:
  - name: hal_atmosic
    url: https://github.com/Atmosic/hal_atmosic
    revision: fbdfe0c17d70528ba239895110ffe7c6e63c04e7
    path: modules/hal/atmosic
  - name: hal_atmosic_lib
    url: https://github.com/Atmosic/hal_atmosic_lib
    revision: ee5e833fed713b19c82efdba19b60ecb112a24d9
    path: modules/hal/atmosic_lib
  - name: mcuboot
    url: https://github.com/Atmosic/mcuboot
    revision: e9f38a28a06fc12cf6afa8d79f48e11d7ffd2350
    path: bootloader/mcuboot
  - name: micro-ecc
    url: https://github.com/Atmosic/micro-ecc
    revision: 70898ab9a98d5f650f8d4d13b1ff01f3f35f0181
    path: modules/crypto/micro-ecc
  - name: zephyr
    url: https://github.com/Atmosic/zephyr
    revision: 24cdd75089db5cb71cc807d377cd974a9f6bfb8f
    west-commands: scripts/west-commands.yml
  - name: cmsis
    url: https://github.com/zephyrproject-rtos/cmsis
    revision: d1b8b20b6278615b00e136374540eb1c00dcabe7
    path: modules/hal/cmsis
    groups:
    - hal
  - name: littlefs
    url: https://github.com/zephyrproject-rtos/littlefs
    revision: ed0531d59ee37f5fb2762bcf2fc8ba4efaf82656
    path: modules/fs/littlefs
    groups:
    - fs
  - name: mbedtls
    url: https://github.com/zephyrproject-rtos/mbedtls
    revision: 4952e1328529ee549d412b498ea71c54f30aa3b1
    path: modules/crypto/mbedtls
    groups:
    - crypto
  - name: tinycrypt
    url: https://github.com/zephyrproject-rtos/tinycrypt
    revision: 1012a3ebee18c15ede5efc8332ee2fc37817670f
    path: modules/crypto/tinycrypt
    groups:
    - crypto
  - name: zcbor
    url: https://github.com/zephyrproject-rtos/zcbor
    revision: 9b07780aca6fb21f82a241ba386ad9b379809337
    path: modules/lib/zcbor
  self:
    path: openair
    west-commands: west/west-commands.yml
