manifest:
  group-filter:
  - -optional
  - -babblesim
  projects:
  - name: hal_atmosic
    url: https://github.com/Atmosic/hal_atmosic
    revision: 959e4cecf89fe1e6abb1f96e283b87ecce710194
    path: modules/hal/atmosic
  - name: hal_atmosic_lib
    url: https://github.com/Atmosic/hal_atmosic_lib
    revision: 1d2e3345d761eb0ee24f7e43d54e59bf3ce06dff
    path: modules/hal/atmosic_lib
  - name: mcuboot
    url: https://github.com/Atmosic/mcuboot
    revision: c274eaef9d5fe62f8b64e7b7d3706971d0358ec1
    path: bootloader/mcuboot
  - name: micro-ecc
    url: https://github.com/Atmosic/micro-ecc
    revision: 1fbaa1f331d4bae752c5e30709669e093e138e6c
    path: modules/crypto/micro-ecc
  - name: zephyr
    url: https://github.com/Atmosic/zephyr
    revision: 826eae664e5e231f48e425b0d6d7660246e2e54b
    west-commands: scripts/west-commands.yml
  - name: cmsis
    url: https://github.com/zephyrproject-rtos/cmsis
    revision: 4b96cbb174678dcd3ca86e11e1f24bc5f8726da0
    path: modules/hal/cmsis
    groups:
    - hal
  - name: littlefs
    url: https://github.com/zephyrproject-rtos/littlefs
    revision: 408c16a909dd6cf128874a76f21c793798c9e423
    path: modules/fs/littlefs
    groups:
    - fs
  - name: mbedtls
    url: https://github.com/zephyrproject-rtos/mbedtls
    revision: 2f24831ee13d399ce019c4632b0bcd440a713f7c
    path: modules/crypto/mbedtls
    groups:
    - crypto
  - name: tinycrypt
    url: https://github.com/zephyrproject-rtos/tinycrypt
    revision: 1012a3ebee18c15ede5efc8332ee2fc37817670f
    path: modules/crypto/tinycrypt
    groups:
    - crypto
  - name: zcbor
    url: https://github.com/zephyrproject-rtos/zcbor
    revision: 75d088037eb237b18e7ec1f47c9ce494b9b95aab
    path: modules/lib/zcbor
  self:
    path: openair
    west-commands: west/west-commands.yml
