manifest:
  group-filter:
  - -babblesim
  - -optional
  - -testing
  projects:
  - name: hal_atmosic_lib
    url: https://github.com/Atmosic/hal_atmosic_lib
    revision: c97f9d9374c1aac58de252d56fd809278d9cfa92
    path: modules/hal/atmosic_lib
  - name: mcuboot
    url: https://github.com/Atmosic/mcuboot
    revision: b5effc5901f5253a69cccae812e4c79851bf4fe5
    path: bootloader/mcuboot
  - name: micro-ecc
    url: https://github.com/Atmosic/micro-ecc
    revision: 1557c622fb555485b6687c877f2276caa4afc6fd
    path: modules/crypto/micro-ecc
  - name: zephyr
    url: https://github.com/Atmosic/zephyr
    revision: 87412b0708b2e4d005ade115f13cc7d245e66d83
    west-commands: scripts/west-commands.yml
  - name: cmsis
    url: https://github.com/zephyrproject-rtos/cmsis
    revision: 512cc7e895e8491696b61f7ba8066b4a182569b8
    path: modules/hal/cmsis
    groups:
    - hal
  - name: cmsis_6
    url: https://github.com/zephyrproject-rtos/CMSIS_6
    revision: 30a859f44ef8ab4dc8f84b03ed586fd16ccf9d74
    path: modules/hal/cmsis_6
    groups:
    - hal
  - name: littlefs
    url: https://github.com/zephyrproject-rtos/littlefs
    revision: 8f5ca347843363882619d8f96c00d8dbd88a8e79
    path: modules/fs/littlefs
    groups:
    - fs
  - name: mbedtls
    url: https://github.com/zephyrproject-rtos/mbedtls
    revision: a3e190fe44c78d1ba67f55979e1257328cc7d0d8
    path: modules/crypto/mbedtls
    groups:
    - crypto
  - name: tf-psa-crypto
    url: https://github.com/zephyrproject-rtos/tf-psa-crypto
    revision: dc575a2ddcc8cb16275d24c42a52eaf79ebe2231
    path: modules/crypto/tf-psa-crypto
    groups:
    - crypto
  - name: zcbor
    url: https://github.com/zephyrproject-rtos/zcbor
    revision: 9164bd18dcd88ff9d9ef98279501fc1093571017
    path: modules/lib/zcbor
  self:
    path: openair
    west-commands: west/west-commands.yml
