manifest:
  group-filter:
  - -babblesim
  - -optional
  projects:
  - name: hal_atmosic_lib
    url: https://github.com/Atmosic/hal_atmosic_lib
    revision: 75456fe2cf4dd1dde2702f4d21d47189b1d0a8c1
    path: modules/hal/atmosic_lib
  - name: mcuboot
    url: https://github.com/Atmosic/mcuboot
    revision: 3bd1226bb899a54e06c5e827390d6f860582df79
    path: bootloader/mcuboot
  - name: micro-ecc
    url: https://github.com/Atmosic/micro-ecc
    revision: 70898ab9a98d5f650f8d4d13b1ff01f3f35f0181
    path: modules/crypto/micro-ecc
  - name: zephyr
    url: https://github.com/Atmosic/zephyr
    revision: 56a42dea095784ab7a49733ec6dacc591c97d4d4
    west-commands: scripts/west-commands.yml
  - name: cmsis
    url: https://github.com/zephyrproject-rtos/cmsis
    revision: 512cc7e895e8491696b61f7ba8066b4a182569b8
    path: modules/hal/cmsis
    groups:
    - hal
  - name: cmsis_6
    url: https://github.com/zephyrproject-rtos/CMSIS_6
    revision: 30a859f44ef8ab4dc8f84b03ed586fd16ccf9d74
    path: modules/hal/cmsis_6
    groups:
    - hal
  - name: littlefs
    url: https://github.com/zephyrproject-rtos/littlefs
    revision: 8f5ca347843363882619d8f96c00d8dbd88a8e79
    path: modules/fs/littlefs
    groups:
    - fs
  - name: mbedtls
    url: https://github.com/zephyrproject-rtos/mbedtls
    revision: c5b06d89c9c498d8fc8659ce31f7e53137b6270f
    path: modules/crypto/mbedtls
    groups:
    - crypto
  - name: zcbor
    url: https://github.com/zephyrproject-rtos/zcbor
    revision: 9b07780aca6fb21f82a241ba386ad9b379809337
    path: modules/lib/zcbor
  self:
    path: openair
    west-commands: west/west-commands.yml
