manifest:
  group-filter:
  - -optional
  - -babblesim
  - -fmna
  projects:
  - name: fmna
    url: git@github.com:Atmosic/fmna.git
    revision: 229279157d3b9a978f60e5de5221d1de58cff122
    path: vendor/fmna
    groups:
    - fmna
  - name: hal_atmosic
    url: https://github.com/Atmosic/hal_atmosic
    revision: 62e4f59b9c24db3203575efafce5c0b071b54564
    path: modules/hal/atmosic
  - name: hal_atmosic_lib
    url: https://github.com/Atmosic/hal_atmosic_lib
    revision: d67fcefdf53482005b09fd11cfe64c62ad8ce365
    path: modules/hal/atmosic_lib
  - name: mcuboot
    url: https://github.com/Atmosic/mcuboot
    revision: 7d0fbe8d5722b222ab84b954d5f3d9f768123d8f
    path: bootloader/mcuboot
  - name: micro-ecc
    url: https://github.com/Atmosic/micro-ecc
    revision: 70898ab9a98d5f650f8d4d13b1ff01f3f35f0181
    path: modules/crypto/micro-ecc
  - name: zephyr
    url: https://github.com/Atmosic/zephyr
    revision: af03f0f69895938494eee4f1d51cf0a7d75cfc7f
    west-commands: scripts/west-commands.yml
  - name: cmsis
    url: https://github.com/zephyrproject-rtos/cmsis
    revision: d1b8b20b6278615b00e136374540eb1c00dcabe7
    path: modules/hal/cmsis
    groups:
    - hal
  - name: littlefs
    url: https://github.com/zephyrproject-rtos/littlefs
    revision: ed0531d59ee37f5fb2762bcf2fc8ba4efaf82656
    path: modules/fs/littlefs
    groups:
    - fs
  - name: mbedtls
    url: https://github.com/zephyrproject-rtos/mbedtls
    revision: 4952e1328529ee549d412b498ea71c54f30aa3b1
    path: modules/crypto/mbedtls
    groups:
    - crypto
  - name: tinycrypt
    url: https://github.com/zephyrproject-rtos/tinycrypt
    revision: 1012a3ebee18c15ede5efc8332ee2fc37817670f
    path: modules/crypto/tinycrypt
    groups:
    - crypto
  - name: zcbor
    url: https://github.com/zephyrproject-rtos/zcbor
    revision: 9b07780aca6fb21f82a241ba386ad9b379809337
    path: modules/lib/zcbor
  self:
    path: openair
    west-commands: west/west-commands.yml
