#!/usr/bin/env python3
"""
@file test_gen_tag_header.py

@brief Unit tests for the data-driven C header generator engine.

These exercise the HeaderGenerator features used by the schema tools
(includes, Doxygen @defgroup blocks, tagged enums, scalar ctype/comment
overrides, verbatim raw lines, and standalone unions) so refactors of the
shared engine cannot silently regress its consumers.

Copyright (C) Atmosic 2026
"""
# pylint: disable=missing-function-docstring,wrong-import-position,import-error

import os
import shutil
import subprocess
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from gen_tag_header import HeaderGenerator, HeaderSection  # noqa: E402


class _StubLoader:  # pylint: disable=too-few-public-methods
    """Minimal schema_loader stand-in for process_union tests.

    Mirrors SchemaLoader.convert_union_to_dict: turns a union config with a
    ``members`` map into the option-struct dict that _gen_union_typedef wants.
    """

    @staticmethod
    def convert_union_to_dict(union_config):
        union_dict = {}
        if "_typedef_name" in union_config:
            union_dict["_typedef_name"] = union_config["_typedef_name"]
        for member_name, fields in union_config.get("members", {}).items():
            union_dict[member_name] = [
                (
                    f["name"],
                    f["type"],
                    f.get("size"),
                    {k: v for k, v in f.items() if k not in ("name", "type", "size")},
                )
                for f in fields
            ]
        return union_dict


class GenTagHeaderTestBase(unittest.TestCase):
    """Common helpers: build a generator and render its output to a string."""

    def setUp(self):
        self._tmp = tempfile.mkdtemp()

    def tearDown(self):
        for name in os.listdir(self._tmp):
            os.remove(os.path.join(self._tmp, name))
        os.rmdir(self._tmp)

    def _make(self, **kwargs):
        return HeaderGenerator(
            brief="Test header",
            output_file="test_out.h",
            output_dir=self._tmp,
            source_file="gen_tag_header.py",
            **kwargs,
        )

    def _render(self, gen):
        path = gen.generate()
        with open(path, encoding="utf-8") as fh:
            return fh.read()

    def _render_struct(self, schema, name="demo_t"):
        gen = self._make()
        gen.add_section(HeaderSection(schema=schema, struct_name=name, defines=[]))
        return self._render(gen)


class TestFileSkeleton(GenTagHeaderTestBase):
    """The unconfigured generator still emits a valid header skeleton."""

    def test_pragma_once_and_warning_banner(self):
        content = self._render(self._make())
        self.assertIn("#pragma once", content)
        self.assertIn("WARNING: DO NOT EDIT THIS FILE", content)
        self.assertIn("Auto-generated from gen_tag_header.py", content)

    def test_cpp_guards_present(self):
        content = self._render(self._make())
        self.assertIn('extern "C" {', content)


class TestIncludes(GenTagHeaderTestBase):
    """`includes` are emitted with correct <> / "" wrapping; opt-in only."""

    def test_includes_emitted_with_correct_wrapping(self):
        gen = self._make(includes=["<stdint.h>", "compiler.h", '"local.h"'])
        content = self._render(gen)
        self.assertIn("#include <stdint.h>", content)
        self.assertIn('#include "compiler.h"', content)
        self.assertIn('#include "local.h"', content)

    def test_no_includes_by_default(self):
        self.assertNotIn("#include", self._render(self._make()))


class TestDocGroup(GenTagHeaderTestBase):
    """`doc_group` wraps the body in a Doxygen @defgroup/@} pair; opt-in."""

    def test_full_doc_group_open_and_close(self):
        gen = self._make(
            doc_group={
                "name": "CALIBRATION",
                "title": "Calibration",
                "ingroup": "DRIVERS",
                "brief": "Calibration data",
            }
        )
        content = self._render(gen)
        self.assertIn("@defgroup CALIBRATION Calibration", content)
        self.assertIn("@ingroup DRIVERS", content)
        self.assertIn("@brief Calibration data", content)
        self.assertIn("@{", content)
        self.assertIn("/// @} CALIBRATION", content)

    def test_minimal_doc_group_defaults_title_to_name(self):
        content = self._render(self._make(doc_group={"name": "GRP"}))
        self.assertIn("@defgroup GRP GRP", content)
        self.assertNotIn("@ingroup", content)
        self.assertIn("/// @} GRP", content)

    def test_no_doc_group_by_default(self):
        content = self._render(self._make())
        self.assertNotIn("@defgroup", content)
        self.assertNotIn("/// @}", content)


class TestEnum(GenTagHeaderTestBase):
    """process_enum: typedef vs tagged, enum/value comments, blank lines."""

    @staticmethod
    def _values():
        return [
            {"name": "ATM_TAG_ATE", "value": "0xb8"},
            {
                "name": "ATM_TAG_GADC_CAL",
                "value": "0xc6",
                "comment": "CAL tags start here",
                "blank_line_before": True,
            },
        ]

    def test_tagged_enum_typedef_false(self):
        gen = self._make()
        HeaderGenerator.process_enum(
            gen, "atm_sec_jrnl_tag", {"values": self._values(), "typedef": False}
        )
        content = self._render(gen)
        self.assertIn("enum atm_sec_jrnl_tag {", content)
        self.assertNotIn("} atm_sec_jrnl_tag;", content)
        self.assertIn("ATM_TAG_ATE = 0xb8,", content)
        self.assertIn("ATM_TAG_GADC_CAL = 0xc6,", content)

    def test_typedef_enum_default(self):
        gen = self._make()
        HeaderGenerator.process_enum(
            gen, "my_enum_t", {"values": [{"name": "A", "value": "0"}]}
        )
        content = self._render(gen)
        self.assertIn("typedef enum {", content)
        self.assertIn("} my_enum_t;", content)

    def test_value_comment_emitted_as_doxygen(self):
        gen = self._make()
        HeaderGenerator.process_enum(
            gen, "atm_sec_jrnl_tag", {"values": self._values(), "typedef": False}
        )
        self.assertIn("/// CAL tags start here", self._render(gen))

    def test_enum_level_comment(self):
        gen = self._make()
        HeaderGenerator.process_enum(
            gen,
            "tag_t",
            {
                "comment": "Platform journal tags",
                "values": [{"name": "A", "value": "0"}],
            },
        )
        self.assertIn("/// Platform journal tags", self._render(gen))

    def test_empty_enum_emits_nothing(self):
        gen = self._make()
        HeaderGenerator.process_enum(gen, "empty_t", {"values": []})
        self.assertNotIn("empty_t", self._render(gen))


class TestScalarFields(GenTagHeaderTestBase):
    """_gen_scalar_field: ctype override, inline comment, char[] arrays."""

    def test_ctype_override_on_char_array(self):
        content = self._render_struct(
            [("lot_id", "s", 6, {"ctype": "char", "comment": "Lot ID"})]
        )
        self.assertIn("char lot_id[6]; /* Lot ID */", content)

    def test_default_ctype_for_byte_array(self):
        content = self._render_struct([("blob", "s", 4, None)])
        self.assertIn("uint8_t blob[4];", content)
        self.assertNotIn("blob[4]; /*", content)

    def test_inline_comment_on_scalar(self):
        content = self._render_struct(
            [("active_bias", "I", None, {"comment": "PMU bias"})]
        )
        self.assertIn("uint32_t active_bias; /* PMU bias */", content)

    def test_pointer_ctype_override(self):
        content = self._render_struct(
            [("addr", "I", None, {"ctype": "volatile uint32_t *"})]
        )
        self.assertIn("volatile uint32_t * addr;", content)


class TestRaw(GenTagHeaderTestBase):
    """process_raw: verbatim C lines with an optional leading comment."""

    def test_emits_verbatim_lines_and_comment(self):
        gen = self._make()
        HeaderGenerator.process_raw(
            gen,
            {
                "comment": "presence check",
                "lines": ["#define CAL_PRESENT(s, f) \\", "    ((s) >= (f))"],
            },
        )
        content = self._render(gen)
        self.assertIn("/// presence check", content)
        self.assertIn("#define CAL_PRESENT(s, f) \\", content)
        self.assertIn("    ((s) >= (f))", content)

    def test_empty_raw_emits_nothing_but_keeps_skeleton(self):
        gen = self._make()
        HeaderGenerator.process_raw(gen, {})
        self.assertIn("#pragma once", self._render(gen))


class TestUnion(GenTagHeaderTestBase):
    """process_union: standalone typedef union with per-width option structs."""

    @staticmethod
    def _config():
        return {
            "comment": "WAR register write/RMW",
            "members": {
                "w": [
                    {
                        "name": "addr",
                        "type": "I",
                        "ctype": "volatile uint32_t *",
                        "comment": "Register address",
                    },
                    {"name": "data", "type": "I"},
                ],
                "b": [
                    {"name": "addr", "type": "B", "ctype": "volatile uint8_t *"},
                    {"name": "data", "type": "B"},
                ],
            },
        }

    def test_generates_typedef_union(self):
        gen = self._make()
        HeaderGenerator.process_union(gen, "mem_rmw_t", self._config(), _StubLoader())
        content = self._render(gen)
        self.assertIn("// WAR register write/RMW", content)
        self.assertIn("typedef union {", content)
        self.assertIn("} __packed mem_rmw_t;", content)
        self.assertIn("} w;", content)
        self.assertIn("} b;", content)
        self.assertIn("volatile uint32_t * addr; /* Register address */", content)
        self.assertIn("volatile uint8_t * addr;", content)


@unittest.skipUnless(shutil.which("clang-format"), "clang-format not available")
class TestClangFormat(GenTagHeaderTestBase):
    """clang_format post-pass: opt-in, normalizes engine output in place."""

    # A pointer member: the engine emits ``volatile uint32_t * addr`` (space
    # before the name); clang-format's Right pointer alignment rewrites it to
    # ``*addr``, so it is a reliable witness of whether formatting ran.
    _PTR_FIELD = [("addr", "I", None, {"ctype": "volatile uint32_t *"})]

    def _render_ptr_struct(self, **kwargs):
        gen = self._make(**kwargs)
        gen.add_section(
            HeaderSection(schema=self._PTR_FIELD, struct_name="demo_t", defines=[])
        )
        path = gen.generate()
        with open(path, encoding="utf-8") as fh:
            return path, fh.read()

    def test_disabled_by_default_leaves_engine_style(self):
        _, content = self._render_ptr_struct()
        self.assertIn("volatile uint32_t * addr;", content)

    def test_enabled_normalizes_and_is_idempotent(self):
        # A literal style avoids depending on a discovered .clang-format file.
        path, content = self._render_ptr_struct(clang_format="LLVM")
        self.assertIn("volatile uint32_t *addr;", content)
        self.assertNotIn("* addr;", content)
        # Output must already satisfy clang-format (no further changes).
        rc = subprocess.run(
            ["clang-format", "--dry-run", "-Werror", "--style=LLVM", path], check=False
        )
        self.assertEqual(rc.returncode, 0)


if __name__ == "__main__":
    unittest.main()
