# Copyright (c) 2026 Atmosic
#
# SPDX-License-Identifier: LicenseRef-Atmosic

openocd_config: "ZEPHYR_BASE/../openair/modules/hal_atmosic/ATM33xx-5/openocd/atmx3_openocd.cfg"
otp_script: "ZEPHYR_BASE/../openair/tools/scripts/atm_otp/ATM33xx-5/atm_otp.py"
