#pragma once

#define PSEQ_STATE_START                                             0
#define PSEQ_STATE_START_BRANCH                                      1
#define PSEQ_STATE_START_2                                           2
#define PSEQ_STATE_START_2_BRANCH                                    3
#define PSEQ_STATE_START_3                                           4
#define PSEQ_STATE_START_3_BRANCH                                    5
#define PSEQ_STATE_START_4                                           6
#define PSEQ_STATE_START_4_BRANCH                                    7
#define PSEQ_STATE_START_5                                           8
#define PSEQ_STATE_START_5_BRANCH                                    9
#define PSEQ_STATE_CPU_ACT_START                                     10
#define PSEQ_STATE_CPU_ACT_START_BRANCH                              11
#define PSEQ_STATE_CPU_ACT_2                                         12
#define PSEQ_STATE_CPU_ACT_2_BRANCH                                  13
#define PSEQ_STATE_CPU_ACT_3                                         14
#define PSEQ_STATE_CPU_ACT_3_BRANCH                                  15
#define PSEQ_STATE_CPU_ACT                                           16
#define PSEQ_STATE_CPU_ACT_BRANCH                                    17
#define PSEQ_STATE_BLE_BOOT_START                                    18
#define PSEQ_STATE_BLE_BOOT_START_BRANCH                             19
#define PSEQ_STATE_BLE_BOOT_2                                        20
#define PSEQ_STATE_BLE_BOOT_2_BRANCH                                 21
#define PSEQ_STATE_BLE_BOOT_3                                        22
#define PSEQ_STATE_BLE_BOOT_3_BRANCH                                 23
#define PSEQ_STATE_BLE_BOOT_4                                        24
#define PSEQ_STATE_BLE_BOOT_4_BRANCH                                 25
#define PSEQ_STATE_BLE_BOOT                                          26
#define PSEQ_STATE_BLE_BOOT_BRANCH                                   27
#define PSEQ_STATE_ACT                                               28
#define PSEQ_STATE_ACT_BRANCH                                        29
#define PSEQ_STATE_RET_ALL_PREQUAL                                   30
#define PSEQ_STATE_RET_ALL_PREQUAL_BRANCH                            31
#define PSEQ_STATE_HIB_PREQUAL                                       32
#define PSEQ_STATE_HIB_PREQUAL_BRANCH                                33
#define PSEQ_STATE_HIB_START                                         34
#define PSEQ_STATE_HIB_START_BRANCH                                  35
#define PSEQ_STATE_HIB_1                                             36
#define PSEQ_STATE_HIB_1_BRANCH                                      37
#define PSEQ_STATE_HIB_2                                             38
#define PSEQ_STATE_HIB_2_BRANCH                                      39
#define PSEQ_STATE_HIB_3                                             40
#define PSEQ_STATE_HIB_3_BRANCH                                      41
#define PSEQ_STATE_HIB_4                                             42
#define PSEQ_STATE_HIB_4_BRANCH                                      43
#define PSEQ_STATE_HIB_5                                             44
#define PSEQ_STATE_HIB_5_BRANCH                                      45
#define PSEQ_STATE_HIB_5B                                            46
#define PSEQ_STATE_HIB_5B_BRANCH                                     47
#define PSEQ_STATE_HIB_6                                             48
#define PSEQ_STATE_HIB_6_BRANCH                                      49
#define PSEQ_STATE_HIB_7                                             50
#define PSEQ_STATE_HIB_7_BRANCH                                      51
#define PSEQ_STATE_HIB                                               52
#define PSEQ_STATE_HIB_BRANCH                                        53
#define PSEQ_STATE_HIB_PREQGRANT                                     54
#define PSEQ_STATE_HIB_PREQGRANT_BRANCH                              55
#define PSEQ_STATE_HIB_UP_START                                      56
#define PSEQ_STATE_HIB_UP_START_BRANCH                               57
#define PSEQ_STATE_HIB_UP_2                                          58
#define PSEQ_STATE_HIB_UP_2_BRANCH                                   59
#define PSEQ_STATE_HIB_UP_2A                                         60
#define PSEQ_STATE_HIB_UP_2A_BRANCH                                  61
#define PSEQ_STATE_HIB_UP_3A                                         62
#define PSEQ_STATE_HIB_UP_3A_BRANCH                                  63
#define PSEQ_STATE_HIB_UP_3B                                         64
#define PSEQ_STATE_HIB_UP_3B_BRANCH                                  65
#define PSEQ_STATE_HIB_UP_3B2                                        66
#define PSEQ_STATE_HIB_UP_3B2_BRANCH                                 67
#define PSEQ_STATE_HIB_UP_3C                                         68
#define PSEQ_STATE_HIB_UP_3C_BRANCH                                  69
#define PSEQ_STATE_HIB_UP_3D                                         70
#define PSEQ_STATE_HIB_UP_3D_BRANCH                                  71
#define PSEQ_STATE_HIB_UP_3E                                         72
#define PSEQ_STATE_HIB_UP_3E_BRANCH                                  73
#define PSEQ_STATE_HIB_UP_4A                                         74
#define PSEQ_STATE_HIB_UP_4A_BRANCH                                  75
#define PSEQ_STATE_HIB_UP_5A                                         76
#define PSEQ_STATE_HIB_UP_5A_BRANCH                                  77
#define PSEQ_STATE_HIB_UP_6A                                         78
#define PSEQ_STATE_HIB_UP_6A_BRANCH                                  79
#define PSEQ_STATE_HIB_UP_7A                                         80
#define PSEQ_STATE_HIB_UP_7A_BRANCH                                  81
#define PSEQ_STATE_HIB_UP_8A                                         82
#define PSEQ_STATE_HIB_UP_8A_BRANCH                                  83
#define PSEQ_STATE_HIB_UP_4                                          84
#define PSEQ_STATE_HIB_UP_4_BRANCH                                   85
#define PSEQ_STATE_HIB_UP_5                                          86
#define PSEQ_STATE_HIB_UP_5_BRANCH                                   87
#define PSEQ_STATE_HIB_UP_6                                          88
#define PSEQ_STATE_HIB_UP_6_BRANCH                                   89
#define PSEQ_STATE_HIB_UP_7                                          90
#define PSEQ_STATE_HIB_UP_7_BRANCH                                   91
#define PSEQ_STATE_HIB_UP_8                                          92
#define PSEQ_STATE_HIB_UP_8_BRANCH                                   93
#define PSEQ_STATE_HIB_UP_9                                          94
#define PSEQ_STATE_HIB_UP_9_BRANCH                                   95
#define PSEQ_STATE_HIB_UP_10                                         96
#define PSEQ_STATE_HIB_UP_10_BRANCH                                  97
#define PSEQ_STATE_RET_ALL_START                                     98
#define PSEQ_STATE_RET_ALL_START_BRANCH                              99
#define PSEQ_STATE_RET_ALL_1                                         100
#define PSEQ_STATE_RET_ALL_1_BRANCH                                  101
#define PSEQ_STATE_RET_ALL_2                                         102
#define PSEQ_STATE_RET_ALL_2_BRANCH                                  103
#define PSEQ_STATE_RET_ALL_3                                         104
#define PSEQ_STATE_RET_ALL_3_BRANCH                                  105
#define PSEQ_STATE_RET_ALL_4                                         106
#define PSEQ_STATE_RET_ALL_4_BRANCH                                  107
#define PSEQ_STATE_RET_ALL_5                                         108
#define PSEQ_STATE_RET_ALL_5_BRANCH                                  109
#define PSEQ_STATE_RET_ALL_6                                         110
#define PSEQ_STATE_RET_ALL_6_BRANCH                                  111
#define PSEQ_STATE_RET_ALL_6B                                        112
#define PSEQ_STATE_RET_ALL_6B_BRANCH                                 113
#define PSEQ_STATE_RET_ALL_7                                         114
#define PSEQ_STATE_RET_ALL_7_BRANCH                                  115
#define PSEQ_STATE_RET_ALL_8                                         116
#define PSEQ_STATE_RET_ALL_8_BRANCH                                  117
#define PSEQ_STATE_RET_ALL_9                                         118
#define PSEQ_STATE_RET_ALL_9_BRANCH                                  119
#define PSEQ_STATE_RET_ALL_XTAL_1                                    120
#define PSEQ_STATE_RET_ALL_XTAL_1_BRANCH                             121
#define PSEQ_STATE_RET_ALL_XTAL_2                                    122
#define PSEQ_STATE_RET_ALL_XTAL_2_BRANCH                             123
#define PSEQ_STATE_RET_ALL_XTAL_3                                    124
#define PSEQ_STATE_RET_ALL_XTAL_3_BRANCH                             125
#define PSEQ_STATE_RET_ALL_NOXTAL_1                                  126
#define PSEQ_STATE_RET_ALL_NOXTAL_1_BRANCH                           127
#define PSEQ_STATE_RET_ALL_UP_3A0                                    128
#define PSEQ_STATE_RET_ALL_UP_3A0_BRANCH                             129
#define PSEQ_STATE_RET_ALL_UP_3A                                     130
#define PSEQ_STATE_RET_ALL_UP_3A_BRANCH                              131
#define PSEQ_STATE_RET_ALL_UP_3B                                     132
#define PSEQ_STATE_RET_ALL_UP_3B_BRANCH                              133
#define PSEQ_STATE_RET_ALL_UP_3B2                                    134
#define PSEQ_STATE_RET_ALL_UP_3B2_BRANCH                             135
#define PSEQ_STATE_RET_ALL_UP_3C                                     136
#define PSEQ_STATE_RET_ALL_UP_3C_BRANCH                              137
#define PSEQ_STATE_RET_ALL_UP_3D                                     138
#define PSEQ_STATE_RET_ALL_UP_3D_BRANCH                              139
#define PSEQ_STATE_RET_ALL_UP_4A                                     140
#define PSEQ_STATE_RET_ALL_UP_4A_BRANCH                              141
#define PSEQ_STATE_RET_ALL_UP_4B                                     142
#define PSEQ_STATE_RET_ALL_UP_4B_BRANCH                              143
#define PSEQ_STATE_RET_ALL_UP_4C                                     144
#define PSEQ_STATE_RET_ALL_UP_4C_BRANCH                              145
#define PSEQ_STATE_RET_ALL_UP_3E                                     146
#define PSEQ_STATE_RET_ALL_UP_3E_BRANCH                              147
#define PSEQ_STATE_RET_ALL_UP_4                                      148
#define PSEQ_STATE_RET_ALL_UP_4_BRANCH                               149
#define PSEQ_STATE_RET_ALL_UP_5                                      150
#define PSEQ_STATE_RET_ALL_UP_5_BRANCH                               151
#define PSEQ_STATE_RET_ALL_UP_6                                      152
#define PSEQ_STATE_RET_ALL_UP_6_BRANCH                               153
#define PSEQ_STATE_RET_ALL_UP_7                                      154
#define PSEQ_STATE_RET_ALL_UP_7_BRANCH                               155
#define PSEQ_STATE_RET_ALL_UP_8                                      156
#define PSEQ_STATE_RET_ALL_UP_8_BRANCH                               157
#define PSEQ_STATE_RET_ALL_UP_9                                      158
