# central_multilink in zephyr prj.conf has max connections as
# 62, which is too high. Limit Atmosic platforms to max of
# 2 connections while testing this sample application.
CONFIG_BT_MAX_CONN=2

# Allow concurrent scanning and initiating.
CONFIG_BT_SCAN_AND_INITIATE_IN_PARALLEL=y
