# Copyright (c) 2025-2026 Atmosic
#
# SPDX-License-Identifier: LicenseRef-Atmosic

CONFIG_RREQ_USE_ARIAD=y
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_LOG_BUFFER_SIZE=2048
CONFIG_LOG_BACKEND_UART_BUFFER_SIZE=2048
CONFIG_LOG_PROCESS_THREAD_SLEEP_MS=100
CONFIG_ATM_LL_HEAP_SIZE=34672

# Ariad not support IQ dump
CONFIG_RREQ_IQ_DUMP=n

# OLED Display
# Support Module
#   - GME: GM009605
#   - GME: GME12864
CONFIG_RREQ_USE_DISPLAY=n
