# Copyright (c) 2026 Atmosic
#
# SPDX-License-Identifier: LicenseRef-Atmosic

CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_ASSERT=y

# Bluetooth configuration
CONFIG_BT=y
CONFIG_BT_ID_MAX=2
CONFIG_BT_SETTINGS=y

# Settings backend
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y

# Shell configuration (optional, for AT command interface)
CONFIG_SHELL=n

# AT Command library
CONFIG_ATM_AT_CMD=y

# Atmosic AT Command Set
CONFIG_AT_CMD_SET=y

# Increase system work queue stack size.
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_AT_CMD_PERIPHERAL=y
