/**
 *******************************************************************************
 *
 * @file base_addr_place_holders.h
 *
 * @brief Base Address manual definitions
 *
 * Copyright (C) Atmosic 2020-2024
 *
 *******************************************************************************
 */

// This is a temporary, manually written companion to base_addr.h for
// paris.  It is a place holder for definitions that aren't yet
// generated by Blueprint but are necessary to build software.  The
// idea is to shrink this -- rather quickly -- until it is empty, at
// which point CHIP_HDR_PLACEHOLDERS in this directory's makefile can
// be unset.

#pragma once

#define CMSDK_EXT_FLASH_NONSECURE_BASE                    0x00200000

#define CMSDK_PDM0_PP_NONSECURE_BASE                      0x40300000
#define CMSDK_PDM1_PP_NONSECURE_BASE                      0x40301000
#define CMSDK_I2S_PP_NONSECURE_BASE                       0x40304000
#define BLE_NONSECURE_BASE                                0x40120000

#define CMSDK_PDM0_PP_SECURE_BASE                         0x50300000
#define CMSDK_PDM1_PP_SECURE_BASE                         0x50301000
#define CMSDK_I2S_PP_SECURE_BASE                          0x50304000
#define BLE_SECURE_BASE                                   0x50120000


////////////////////////////////////////////////////////////////////////////////
// Selectively move above this line definitions from the section below if they
// are needed but not generated by blueprint
////////////////////////////////////////////////////////////////////////////////

#if 0
/*---------- AT_APB_OLED ----------*/
typedef struct {
  __IO uint32_t  CONTROL;
  __IO uint32_t  CHARS_0A;
  __IO uint32_t  CHARS_0B;
  __IO uint32_t  CHARS_0C;
  __IO uint32_t  CHARS_0D;
  __IO uint32_t  CHARS_1A;
  __IO uint32_t  CHARS_1B;
  __IO uint32_t  CHARS_1C;
  __IO uint32_t  CHARS_1D;
  __IO uint32_t  CHARS_2A;
  __IO uint32_t  CHARS_2B;
  __IO uint32_t  CHARS_2C;
  __IO uint32_t  CHARS_2D;
  __IO uint32_t  CHARS_3A;
  __IO uint32_t  CHARS_3B;
  __IO uint32_t  CHARS_3C;
  __IO uint32_t  CHARS_3D;
  __I  uint32_t  STATUS;
       uint32_t  RESERVED0[1005];
  __I  uint32_t  CORE_ID;
} CMSDK_AT_APB_OLED_TypeDef;

#define CMSDK_DPR_NONSECURE_BASE                          0x4016F000

#define CMSDK_DPR_NONSECURE                               ((CMSDK_AT_APB_DPR_TypeDef *) CMSDK_DPR_NONSECURE_BASE)

#endif // 0
