/**
 *****************************************************************************
 *
 * @file pseq_states.h
 *
 * @brief PSEQ State Machine definitions
 *
 * Copyright (C) Atmosic 2022-2024
 *
 *****************************************************************************
 */

#pragma once

#define PSEQ_STATE_START                                             0
#define PSEQ_STATE_START_BRANCH                                      1
#define PSEQ_STATE_START_2                                           2
#define PSEQ_STATE_START_2_BRANCH                                    3
#define PSEQ_STATE_START_3                                           4
#define PSEQ_STATE_START_3_BRANCH                                    5
#define PSEQ_STATE_START_4                                           6
#define PSEQ_STATE_START_4_BRANCH                                    7
#define PSEQ_STATE_CPU_ACT_START                                     8
#define PSEQ_STATE_CPU_ACT_START_BRANCH                              9
#define PSEQ_STATE_CPU_ACT_2                                         10
#define PSEQ_STATE_CPU_ACT_2_BRANCH                                  11
#define PSEQ_STATE_CPU_ACT_3                                         12
#define PSEQ_STATE_CPU_ACT_3_BRANCH                                  13
#define PSEQ_STATE_CPU_ACT                                           14
#define PSEQ_STATE_CPU_ACT_BRANCH                                    15
#define PSEQ_STATE_BLE_BOOT_START                                    16
#define PSEQ_STATE_BLE_BOOT_START_BRANCH                             17
#define PSEQ_STATE_BLE_BOOT_2                                        18
#define PSEQ_STATE_BLE_BOOT_2_BRANCH                                 19
#define PSEQ_STATE_BLE_BOOT_3                                        20
#define PSEQ_STATE_BLE_BOOT_3_BRANCH                                 21
#define PSEQ_STATE_BLE_BOOT_4                                        22
#define PSEQ_STATE_BLE_BOOT_4_BRANCH                                 23
#define PSEQ_STATE_BLE_BOOT                                          24
#define PSEQ_STATE_BLE_BOOT_BRANCH                                   25
#define PSEQ_STATE_ACT                                               26
#define PSEQ_STATE_ACT_BRANCH                                        27
#define PSEQ_STATE_HIB_START                                         28
#define PSEQ_STATE_HIB_START_BRANCH                                  29
#define PSEQ_STATE_HIB_1                                             30
#define PSEQ_STATE_HIB_1_BRANCH                                      31
#define PSEQ_STATE_HIB_2                                             32
#define PSEQ_STATE_HIB_2_BRANCH                                      33
#define PSEQ_STATE_HIB_3                                             34
#define PSEQ_STATE_HIB_3_BRANCH                                      35
#define PSEQ_STATE_HIB_4                                             36
#define PSEQ_STATE_HIB_4_BRANCH                                      37
#define PSEQ_STATE_HIB_5                                             38
#define PSEQ_STATE_HIB_5_BRANCH                                      39
#define PSEQ_STATE_HIB_6                                             40
#define PSEQ_STATE_HIB_6_BRANCH                                      41
#define PSEQ_STATE_HIB_7                                             42
#define PSEQ_STATE_HIB_7_BRANCH                                      43
#define PSEQ_STATE_HIB                                               44
#define PSEQ_STATE_HIB_BRANCH                                        45
#define PSEQ_STATE_HIB_SHUB_STOP                                     46
#define PSEQ_STATE_HIB_SHUB_STOP_BRANCH                              47
#define PSEQ_STATE_HIB_UP_START                                      48
#define PSEQ_STATE_HIB_UP_START_BRANCH                               49
#define PSEQ_STATE_HIB_UP_2                                          50
#define PSEQ_STATE_HIB_UP_2_BRANCH                                   51
#define PSEQ_STATE_HIB_UP_3A                                         52
#define PSEQ_STATE_HIB_UP_3A_BRANCH                                  53
#define PSEQ_STATE_HIB_UP_3B                                         54
#define PSEQ_STATE_HIB_UP_3B_BRANCH                                  55
#define PSEQ_STATE_HIB_UP_3C                                         56
#define PSEQ_STATE_HIB_UP_3C_BRANCH                                  57
#define PSEQ_STATE_HIB_UP_3D                                         58
#define PSEQ_STATE_HIB_UP_3D_BRANCH                                  59
#define PSEQ_STATE_HIB_UP_3E                                         60
#define PSEQ_STATE_HIB_UP_3E_BRANCH                                  61
#define PSEQ_STATE_HIB_UP_4                                          62
#define PSEQ_STATE_HIB_UP_4_BRANCH                                   63
#define PSEQ_STATE_HIB_UP_5                                          64
#define PSEQ_STATE_HIB_UP_5_BRANCH                                   65
#define PSEQ_STATE_HIB_UP_6                                          66
#define PSEQ_STATE_HIB_UP_6_BRANCH                                   67
#define PSEQ_STATE_HIB_UP_7                                          68
#define PSEQ_STATE_HIB_UP_7_BRANCH                                   69
#define PSEQ_STATE_HIB_UP_8                                          70
#define PSEQ_STATE_HIB_UP_8_BRANCH                                   71
#define PSEQ_STATE_HIB_UP_9                                          72
#define PSEQ_STATE_HIB_UP_9_BRANCH                                   73
#define PSEQ_STATE_HIB_UP_10                                         74
#define PSEQ_STATE_HIB_UP_10_BRANCH                                  75
#define PSEQ_STATE_HIB_BLE_START                                     76
#define PSEQ_STATE_HIB_BLE_START_BRANCH                              77
#define PSEQ_STATE_HIB_BLE_1                                         78
#define PSEQ_STATE_HIB_BLE_1_BRANCH                                  79
#define PSEQ_STATE_HIB_BLE_2                                         80
#define PSEQ_STATE_HIB_BLE_2_BRANCH                                  81
#define PSEQ_STATE_HIB_BLE_3                                         82
#define PSEQ_STATE_HIB_BLE_3_BRANCH                                  83
#define PSEQ_STATE_HIB_BLE_4                                         84
#define PSEQ_STATE_HIB_BLE_4_BRANCH                                  85
#define PSEQ_STATE_HIB_BLE_5                                         86
#define PSEQ_STATE_HIB_BLE_5_BRANCH                                  87
#define PSEQ_STATE_HIB_BLE_6                                         88
#define PSEQ_STATE_HIB_BLE_6_BRANCH                                  89
#define PSEQ_STATE_HIB_BLE_7                                         90
#define PSEQ_STATE_HIB_BLE_7_BRANCH                                  91
#define PSEQ_STATE_HIB_BLE                                           92
#define PSEQ_STATE_HIB_BLE_BRANCH                                    93
#define PSEQ_STATE_SHUB_ADV_UP_START                                 94
#define PSEQ_STATE_SHUB_ADV_UP_START_BRANCH                          95
#define PSEQ_STATE_SHUB_BLE_RET_UP_2                                 96
#define PSEQ_STATE_SHUB_BLE_RET_UP_2_BRANCH                          97
#define PSEQ_STATE_SHUB_BLE_RET_UP_3                                 98
#define PSEQ_STATE_SHUB_BLE_RET_UP_3_BRANCH                          99
#define PSEQ_STATE_SHUB_BLE_RET_UP_4                                 100
#define PSEQ_STATE_SHUB_BLE_RET_UP_4_BRANCH                          101
#define PSEQ_STATE_SHUB_BLE_RET_UP                                   102
#define PSEQ_STATE_SHUB_BLE_RET_UP_BRANCH                            103
#define PSEQ_STATE_SHUB_ADV                                          104
#define PSEQ_STATE_SHUB_ADV_BRANCH                                   105
#define PSEQ_STATE_RET_ALL_START                                     106
#define PSEQ_STATE_RET_ALL_START_BRANCH                              107
#define PSEQ_STATE_RET_ALL_1                                         108
#define PSEQ_STATE_RET_ALL_1_BRANCH                                  109
#define PSEQ_STATE_RET_ALL_2                                         110
#define PSEQ_STATE_RET_ALL_2_BRANCH                                  111
#define PSEQ_STATE_RET_ALL_3                                         112
#define PSEQ_STATE_RET_ALL_3_BRANCH                                  113
#define PSEQ_STATE_RET_ALL_4                                         114
#define PSEQ_STATE_RET_ALL_4_BRANCH                                  115
#define PSEQ_STATE_RET_ALL_5                                         116
#define PSEQ_STATE_RET_ALL_5_BRANCH                                  117
#define PSEQ_STATE_RET_ALL_6                                         118
#define PSEQ_STATE_RET_ALL_6_BRANCH                                  119
#define PSEQ_STATE_RET_ALL_7                                         120
#define PSEQ_STATE_RET_ALL_7_BRANCH                                  121
#define PSEQ_STATE_RET_ALL_XTAL_1                                    122
#define PSEQ_STATE_RET_ALL_XTAL_1_BRANCH                             123
#define PSEQ_STATE_RET_ALL_XTAL_2                                    124
#define PSEQ_STATE_RET_ALL_XTAL_2_BRANCH                             125
#define PSEQ_STATE_RET_ALL_XTAL_3                                    126
#define PSEQ_STATE_RET_ALL_XTAL_3_BRANCH                             127
#define PSEQ_STATE_RET_ALL_XTAL_4                                    128
#define PSEQ_STATE_RET_ALL_XTAL_4_BRANCH                             129
#define PSEQ_STATE_RET_ALL_NOXTAL_1                                  130
#define PSEQ_STATE_RET_ALL_NOXTAL_1_BRANCH                           131
#define PSEQ_STATE_RET_ALL_NOXTAL_2                                  132
#define PSEQ_STATE_RET_ALL_NOXTAL_2_BRANCH                           133
#define PSEQ_STATE_RET_ALL_UP_3A                                     134
#define PSEQ_STATE_RET_ALL_UP_3A_BRANCH                              135
#define PSEQ_STATE_RET_ALL_UP_3B                                     136
#define PSEQ_STATE_RET_ALL_UP_3B_BRANCH                              137
#define PSEQ_STATE_RET_ALL_UP_3C                                     138
#define PSEQ_STATE_RET_ALL_UP_3C_BRANCH                              139
#define PSEQ_STATE_RET_ALL_UP_3D                                     140
#define PSEQ_STATE_RET_ALL_UP_3D_BRANCH                              141
#define PSEQ_STATE_RET_ALL_UP_4                                      142
#define PSEQ_STATE_RET_ALL_UP_4_BRANCH                               143
#define PSEQ_STATE_RET_ALL_UP_5                                      144
#define PSEQ_STATE_RET_ALL_UP_5_BRANCH                               145
#define PSEQ_STATE_RET_ALL_UP_6                                      146
#define PSEQ_STATE_RET_ALL_UP_6_BRANCH                               147
#define PSEQ_STATE_RET_ALL_UP_7                                      148
#define PSEQ_STATE_RET_ALL_UP_7_BRANCH                               149
#define PSEQ_STATE_RET_ALL_UP_8                                      150
#define PSEQ_STATE_RET_ALL_UP_8_BRANCH                               151
#define PSEQ_STATE_RET_ALL_UP_9                                      152
#define PSEQ_STATE_RET_ALL_UP_9_BRANCH                               153
#define PSEQ_STATE_BLE_ONLY_LP_START                                 154
#define PSEQ_STATE_BLE_ONLY_LP_START_BRANCH                          155
#define PSEQ_STATE_BLE_ONLY_LP_1                                     156
#define PSEQ_STATE_BLE_ONLY_LP_1_BRANCH                              157
#define PSEQ_STATE_BLE_ONLY_LP_2                                     158
#define PSEQ_STATE_BLE_ONLY_LP_2_BRANCH                              159
#define PSEQ_STATE_BLE_ONLY_LP_3                                     160
#define PSEQ_STATE_BLE_ONLY_LP_3_BRANCH                              161
#define PSEQ_STATE_BLE_ONLY_LP_4                                     162
#define PSEQ_STATE_BLE_ONLY_LP_4_BRANCH                              163
#define PSEQ_STATE_BLE_ONLY_LP_5                                     164
#define PSEQ_STATE_BLE_ONLY_LP_5_BRANCH                              165
#define PSEQ_STATE_BLE_ONLY_XTAL_1                                   166
#define PSEQ_STATE_BLE_ONLY_XTAL_1_BRANCH                            167
#define PSEQ_STATE_BLE_ONLY_BOTTOM                                   168
#define PSEQ_STATE_BLE_ONLY_BOTTOM_BRANCH                            169
#define PSEQ_STATE_BLE_ONLY_UP_1                                     170
#define PSEQ_STATE_BLE_ONLY_UP_1_BRANCH                              171
#define PSEQ_STATE_BLE_ONLY_UP_2                                     172
#define PSEQ_STATE_BLE_ONLY_UP_2_BRANCH                              173
#define PSEQ_STATE_BLE_ONLY_UP_3                                     174
#define PSEQ_STATE_BLE_ONLY_UP_3_BRANCH                              175
#define PSEQ_STATE_BLE_ONLY_UP_4                                     176
#define PSEQ_STATE_BLE_ONLY_UP_4_BRANCH                              177
#define PSEQ_STATE_BLE_ONLY_UP_5                                     178
#define PSEQ_STATE_BLE_ONLY_UP_5_BRANCH                              179
#define PSEQ_STATE_BLE_ONLY_UP_6                                     180
#define PSEQ_STATE_BLE_ONLY_UP_6_BRANCH                              181
#define PSEQ_STATE_BLE_ONLY_UP_7                                     182
#define PSEQ_STATE_BLE_ONLY_UP_7_BRANCH                              183
#define PSEQ_STATE_BLE_ONLY_UP_8                                     184
#define PSEQ_STATE_BLE_ONLY_UP_8_BRANCH                              185
#define PSEQ_STATE_BLE_ONLY_UP_9                                     186
#define PSEQ_STATE_BLE_ONLY_UP_9_BRANCH                              187
#define PSEQ_STATE_BLE_ONLY_UP_10                                    188
#define PSEQ_STATE_BLE_ONLY_UP_10_BRANCH                             189
#define PSEQ_STATE_BLE_ONLY_UP_11                                    190
