# Copyright (c) 2025-2026 Atmosic
#
# SPDX-License-Identifier: LicenseRef-Atmosic

# Enable MCUmgr with image and OS management command groups
CONFIG_ATM_MCUMGR=y

# Enable MCUmgr Bluetooth transport with encryption (level 2)
CONFIG_MCUMGR_TRANSPORT_BT=y
CONFIG_MCUMGR_TRANSPORT_BT_PERM_RW_ENCRYPT=y
