# STACK SIZE
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_LOG=y

# DRIVER
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_DISPLAY=y
CONFIG_LED=y

# BT
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_SMP=y
CONFIG_BT_PRIVACY=y
CONFIG_BT_BUF_ACL_RX_SIZE=502
CONFIG_BT_ATT_PREPARE_COUNT=2
CONFIG_BT_MAX_PAIRED=1
CONFIG_BT_MAX_CONN=1

CONFIG_BT_DEVICE_NAME="Atmosic_ESL"
CONFIG_BT_DEVICE_APPEARANCE=2754

# DIS
CONFIG_BT_DIS=y
CONFIG_BT_DIS_PNP=y
CONFIG_BT_DIS_MANUF_NAME_STR="Atmosic Tech."
CONFIG_BT_DIS_PNP_VID_SRC=2
CONFIG_BT_DIS_PNP_VID=0x045E
CONFIG_BT_DIS_PNP_PID=0x0040
CONFIG_BT_DIS_PNP_VER=0x0300

# SETTINGS
CONFIG_BT_SETTINGS=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_ATM_SETTINGS=y

# BT STKLIB
CONFIG_ATMWSTK_CPD200=y

# ESLS
CONFIG_BT_ESLS=y
CONFIG_BT_ESLS_IMAGE_NUM=2
# Need to be CONFIG_BT_ESLS_IMAGE_NUM + 1 (1 for BT_OTS_DIR_LIST_OBJ)
CONFIG_BT_OTS_MAX_OBJ_CNT=3
CONFIG_BT_ESLS_IMAGE_MAX_SIZE=12288
CONFIG_BT_ESLS_ADV_MANU_DATA_MAX=6
CONFIG_BT_ESLS_LED_NUM=1

# STACK SENTINEL
CONFIG_STACK_SENTINEL=y

# Need to enable for power consumption measure
#CONFIG_ENS210_TEMPERATURE_SINGLE=y
#CONFIG_ENS210_HUMIDITY_SINGLE=y

CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=n
CONFIG_APP_WORK_Q=y

# VENDOR API COMMAND
CONFIG_ATM_VENDOR_API=y
CONFIG_VND_API_SET_ADV_TX_POWER=y
CONFIG_VND_API_SET_CON_TX_POWER=y
