# Copyright (c) 2026 Atmosic
#
# SPDX-License-Identifier: LicenseRef-Atmosic

# Enable MCUmgr with image and OS management command groups
CONFIG_ATM_MCUMGR=y

# Enable MCUmgr UART transport
CONFIG_UART_MCUMGR=y
CONFIG_MCUMGR_TRANSPORT_UART=y
